### ISSUE TITLE
Cloud Sync (Google Cloud Drive/Dropbox etc)

### ISSUE THREAD

**Issue by majolo** [Zuntek/WeekToDoWeb#76]
Hey I started using this and it seems like a great app, however without it syncing between my work and personal machines it doesn't quite fit my workflow.

It would be great if I could get it to sync via my personal Google Cloud Drive or similar online file store.

**Comment by merodriguez9112** [comment]
Hi @majolo. Yes, it's in the roadmap :)

**Comment by merodriguez9112** [comment]
Closing this as duplicate in https://github.com/Zuntek/WeekToDoWeb/issues/58.
