### ISSUE TITLE
[feature request] Repeating tasks

### ISSUE THREAD

**Issue by seapancake** [Zuntek/WeekToDoWeb#77]
Love the app, it's minimal yet still supports sub-tasks and notes!

The one big thing for me is I have a weekly schedule and I'd love a way to make a task repeat on a certain day.

**Comment by merodriguez9112** [comment]
Hi @seapancake thanks for writing, yes I know is a good thing to have, I'll be working on it for the next release of the app :)

**Comment by burtek** [comment]
+1 on the idea, came here to suggest it myself.

Btw, just installed and love the app already!

**Comment by cocoonkid** [comment]
+1  Really important imho!

**Comment by merodriguez9112** [comment]
I was finally able to add this functionality in version 1.8. I am closing this issue
