### ISSUE TITLE
This is not the app's source code

### ISSUE THREAD

**Issue by alesya-h** [Zuntek/WeekToDoWeb#79]
Maybe I misunderstand something, but it's not the app itself - it's just the source code of the landing page. I wanted to debug an issue I have, but I couldn't find any source code of the app. You state in this repo that the app's license is MIT, and use Releases here to distribute it, but it doesn't seem to be opensource at all. Can you point me to the source code please or clearly indicate that the app is just Freeware?

**Comment by merodriguez9112** [comment]
Hi @alesya-h thanks for writing. Yes you are totally right, the repo was original open source but in some point I don't had any contribution and I decided to close it and keep working by my self and try to find a way to sustend the project development and the cost of the services. Then I moved the builds and the translation to this public repo. I will add that info in the readme file of this project. Thanks.

**Comment by merodriguez9112** [comment]
Please if you have any suggestion or feedback about it please let me know

**Comment by merodriguez9112** [comment]
Closing this issue

> Hi @alesya-h thanks for writing. Yes you are totally right, the repo was original open source but in some point I don't had any contribution and I decided to close it and keep working by my self and try to find a way to sustend the project development and the cost of the services. Then I moved the builds and the translation to this public repo. I will add that info in the readme file of this project. Thanks.
