### ISSUE TITLE
Week2Do 1.7.0 on aarch64 m1 does start but does not show the GUI.

### ISSUE THREAD

**Issue by cocoonkid** [Zuntek/WeekToDoWeb#84]
the version before worked without issues.

I seems to run correctly.

![CleanShot 2022-04-16 at 08 10 28@2x](https://user-images.githubusercontent.com/43231640/163664021-e7f4c36d-bdff-4384-a9a0-6830ae137645.jpg)

But the GUI is nowhere to be seen.

I noticed that I can quit it via right-clicking the Icon and "Quit" but it still is open in the task manager as is it's helper.

Also the old Logo was much cooler :-)

**Comment by cocoonkid** [comment]
I solved it now by deleting the folders above and restarting.  Not a biggie. Had only two tasks left but that should be taken care of.

It seems there is a missing state reset ?

**Comment by merodriguez9112** [comment]
Hi @cocoonkid thanks for report that. I had a lot of problems to release this version for macOS, I don't have a mac and sadly this cross-platform solution need a different implementation for each system, so I had to do it blind for macOS :/

Can you give me some feedbacks about these problems please ?

> But the GUI is nowhere to be seen.
What do you mean with that ? not even the icon appears on the tray? Now the app is supposed to run at system startup and the first time it is opened it opens minimized in the tray, I'm not sure if it had been this

- In this version, the app should keep working in background when you close the windows (I mean the main windows) but when you click the Tray icon and click exit it should kill all the process. is this not working like this ?

- When you say that the other icon was better now I doubt. The system should display the same icon for the app in the dock as before and a small white icon on the top bar. This is so ? Or is the white icon appearing everywhere?

thanks for writing and sorry for the interrogation hahaha. Regards

**Comment by cocoonkid** [comment]
The problem reappeared today. It was happening when CleanMyMac tried to  close the app for system cleanup.

It works with all other apps so It must be something specific to WeekToDo.


I was able to drill the issue down to deleting ~/Library/SavedApplicationState/weektodo-netlify,app.saved.state and it worked again.

Deleting the ~/Library/Application Support/weektodo folder initially did not make it work again...next time will test without deleting this folder to be 100% sure, but I am already like 99%.

Re  Icon:

It shows the white icon with  the blueblack W .  But last version it showed me one similar to the electron icon :)
Anyway I got used to the  new one already :+1: 

> In this version, the app should keep working in background when you close the windows (I mean the main windows) but when you click the Tray icon and click exit it should kill all the process. is this not working like this ?

I tried that now and NO it does NOT kill the background processes.  I suspect that is the Issue.

No worries about the questions. I want this to work as much as you!

**Comment by cocoonkid** [comment]
@merodriguez9112 

Okay today it happened again. And I had to delete all the folders to restore it to the initial state.
This was independent of CleanMyMac.

It is definitively not proper closing down and this is where the corruption occures.

**Comment by merodriguez9112** [comment]
Hey @cocoonkid thanks for all your feedbacks, I definitely have to find a way to run macoOS and do several tests to see if I can figure out what's going on. Can I know what version of macOS you use? Thanks in advance :)

**Comment by merodriguez9112** [comment]
just to be clear, the problem is that it opens the window and stays blank ?

**Comment by cocoonkid** [comment]
This issue continues to exist..

**Comment by cocoonkid** [comment]
I found what the issue was.> I never noticed the menu bar icon which opens and closes the main window.

This should be optimized. Clicking the icon in the app bar should also show the window.
