### ISSUE TITLE
[feature request] AUR package for Arch Linux

### ISSUE THREAD

**Issue by cocoonkid** [Zuntek/WeekToDoWeb#90]
https://wiki.archlinux.org/title/PKGBUILD

This would be so awesome!

I'm too scared to wreck my system to  use the `dpkg -i  WeekToDo_1.7.0_amd64.deb`.

from [Stackexchange - [Installing a .deb package on Arch - Is it possible?](https://unix.stackexchange.com/questions/83540/installing-a-deb-package-on-arch-is-it-possible)

> Not the recommended way (possibly dangerous)
> This method attempts to install the package using the debian packaging format on Arch, which is not recommended due to possible danger of corrupting your installation. If using this method it is recommended to be ready with a rescue disc image of Arch & backup of the user data/space.
> 
> Install [dpkg](https://aur.archlinux.org/packages/dpkg/) using yay:
> 
> ` yay -S dpkg`
> Install the debian package using dpkg:
> 
>  `sudo dpkg -i package_name.deb`

**Comment by cocoonkid** [comment]
okay I quickly pushed a clone of my system to a VM and tried it out.


```

❯ sudo dpkg -i WeekToDo_1.7.0_amd64.deb
Selecting previously unselected package weektodo.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack WeekToDo_1.7.0_amd64.deb ...
Unpacking weektodo (1.7.0) ...
dpkg: dependency problems prevent configuration of weektodo:
 weektodo depends on libgtk-3-0; however:
  Package libgtk-3-0 is not installed.
 weektodo depends on libnotify4; however:
  Package libnotify4 is not installed.
 weektodo depends on libnss3; however:
  Package libnss3 is not installed.
 weektodo depends on libxss1; however:
  Package libxss1 is not installed.
 weektodo depends on libxtst6; however:
  Package libxtst6 is not installed.
 weektodo depends on xdg-utils; however:
  Package xdg-utils is not installed.
 weektodo depends on libatspi2.0-0; however:
  Package libatspi2.0-0 is not installed.
 weektodo depends on libuuid1; however:
  Package libuuid1 is not installed.
 weektodo depends on libsecret-1-0; however:
  Package libsecret-1-0 is not installed.

dpkg: error processing package weektodo (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 weektodo



❯ sudo pacman -S libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0
error: target not found: libgtk-3-0
error: target not found: libnotify4
error: target not found: libnss3
error: target not found: libxss1
error: target not found: libxtst6
warning: xdg-utils-1.1.3+19+g9816ebb-1 is up to date -- reinstalling
error: target not found: libatspi2.0-0
error: target not found: libuuid1
error: target not found: libsecret-1-0
```

I can try further but first have to untangle how to get  the  deps.

If that helps to achieve having a solution for Arch Linux of course. 

Let me know before I sink more time into this.  Thanks!

**Comment by merodriguez9112** [comment]
Hey @cocoonkid . I have never used Arch, I thought that with Snap you could install the application on Arch  https://snapcraft.io/install/weektodo/arch.

Do we have any problems with this type of installation? Or is it not used ? Would we solve that problem with an appImage ?

**Comment by cocoonkid** [comment]
It is my personal opinion  gathered over time but I feel the appImage is a hack and Snap is hated for reasons and on the way out if I'm not mistaken. Both are unnecessary bloat even if well meaning in spirit.

If you give me the Go I will work on this. Always wanted to learn how to write my own AUR packages anyways.

**Comment by merodriguez9112** [comment]
Thanks @cocoonkid I've been reviewing the build options for Arch and this is what Electron can offer

https://www.electron.build/configuration/linux

> The top-level [linux](https://www.electron.build/configuration/configuration#Configuration-linux) key contains set of options instructing electron-builder on how it should build Linux targets. These options applicable for any Linux target.

> target = AppImage String | [TargetConfiguration](https://www.electron.build/cli#targetconfiguration) - Target package type: list of AppImage, snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir.

The most common that people use for Cross-platform are AppImages or I think also Flatpack, in the case of Arch I think a .pacman could be created.

**Comment by cocoonkid** [comment]
yes. that can work and be released as weektodo-bin.

https://old.reddit.com//r/archlinux/comments/psg0vg/deploying_a_prebuilt_package_to_the_aur_or/

or manually downloaded and installed.

**Comment by cocoonkid** [comment]
@merodriguez9112 Thanks for the pacman package. This is moving nearer.

**Comment by cocoonkid** [comment]
Agreed. Thanks for taking the time to explain.
